---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false

  roles:
    - geerlingguy.git
  
  # tasks:
  # - name: install cinc-auditor
  #     shell: "bash /tmp/install.sh -s -- -P cinc-auditor -v 4"

  #   - name: Execute cinc-auditor tests
  #     command: "/opt/cinc-auditor/bin/cinc-auditor exec --no-show-progress --no-color --no-distinct-exit supermarket://dev-sec/linux-baseline"
  #     register: test_results
  #     changed_when: false
  #     ignore_errors: true

  #   - name: Display details about the cinc-auditor results
  #     debug:
  #       msg: "{{ test_results.stdout_lines }}"

  #   - name: Fail when tests fail
  #     fail:
  #       msg: "Inspec failed to validate"
  #     when: test_results.rc != 0
